# Generated by Django 2.1.1 on 2018-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agentid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
                ('servstar', models.IntegerField(default=0)),
                ('realstar', models.IntegerField(default=0)),
                ('profstar', models.IntegerField(default=0)),
                ('certificated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentEstate',
            fields=[
                ('agent_estate_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_agent_estate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('distid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('estateid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hot', models.IntegerField(blank=True, default=0, null=True)),
                ('intro', models.CharField(blank=True, max_length=511, null=True)),
            ],
            options={
                'db_table': 'tb_estate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('houseid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('totalfloor', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('priceunit', models.CharField(max_length=10)),
                ('detail', models.CharField(blank=True, max_length=511, null=True)),
                ('mainphoto', models.CharField(max_length=255)),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('hassubway', models.IntegerField()),
                ('isshared', models.IntegerField()),
                ('hasagentfees', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_house_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('photoid', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_house_photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseTag',
            fields=[
                ('house_tag_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_house_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('typeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_house_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('logid', models.BigAutoField(primary_key=True, serialize=False)),
                ('ipaddr', models.CharField(max_length=255)),
                ('logdate', models.DateTimeField(auto_now_add=True)),
                ('devcode', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'tb_login_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordid', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorddate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('realname', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=32)),
                ('point', models.IntegerField(default=0)),
                ('lastvisit', models.DateTimeField(auto_now_add=True)),
                ('isagent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_user',
                'managed': False,
            },
        ),
    ]
